### ISSUE TITLE
libencoder and libdecoder infringe on the GPL

### ISSUE THREAD

**Issue by oliv3r** [allwinner-zh/media-codec-lib#1]
libdecoder.so and libencoder.so are infringing on the GPL, there is GPL source code within them. This rquires that both libencoder and libdecoder.so be open source themselves.

I suggest to put the full source code of these libraries in the media-codec repository, and delete this repostiory.

**Comment by allwinner-zh** [comment]
The library is just the hardware module implemented in user space, and the code is all writed by Allwinner.
Can you provide any evidence that there is some GPL source ocde within them?

**Comment by oliv3r** [comment]
H264FillDefaultRefList() and a lot of code around it is straight out of 
the libavcodec h264 decoder. The original name for that function is
ff_h264_fill_default_ref_list() in libavcodec/h264_refs.c:
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/h264_refs.c#L115
This is new, as some totally different code for h264 was available in 
the previous versions of the cedarx binaries.

For more information, see the linux-sunxi maililng list.
